"""Add invoice fields to Payment

Revision ID: 46280233f3d3
Revises: 24ad654c7914
Create Date: 2025-01-12 19:23:04.351117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46280233f3d3'
down_revision = '24ad654c7914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('invoice_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('services_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('invoice_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('invoice_date')
        batch_op.drop_column('total_cost')
        batch_op.drop_column('services_details')
        batch_op.drop_column('invoice_sent')
        batch_op.drop_column('invoice_name')

    # ### end Alembic commands ###
